// plugins/fontawesome.ts (universel SSR + client)
import { library, config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
// Évite l'injection automatique du CSS côté client (préférable avec SSR)
config.autoAddCss = false
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

// Import ciblé des icônes utilisées (pour limiter le bundle)
import {
  faSearch,
  faRefresh,
  faEye,
  faEyeSlash,
  faDownload,
  faEdit,
  faTimes,
  faPlus,
  faCheck,
  faTag,
  faDollarSign,
  faUser,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faQrcode,
  faSave,
  faTrash,
  faCog,
  faInfoCircle,
  faExclamationTriangle,
  faCheckCircle,
  faTimesCircle,
  faList,
  faSignInAlt,
  faEnvelope,
  faLock,
  faKey,
  faSignOutAlt,
  faHome,
  faTachometerAlt,
  faUserCircle,
  faQuestionCircle,
  faUsers,
  faBarcode,
  // Icônes ajoutées pour corriger les erreurs runtime
  faRocket,
  faBolt,
  faFolderOpen,
  faShieldHalved,
  faChartBar,
  faMobileScreenButton,
  faUserPlus,
  faBuilding,
  faWeightHanging,
  // Autres icônes utilisées dans le projet
  faSpinner,
  faPaperPlane,
  faArrowLeft,
  faShield,
  faTruck,
  faBox,
  faCalendar,
  faShare,
  faArrowsRotate,
  faRightToBracket,
  faRightFromBracket,
  faGaugeHigh
} from '@fortawesome/free-solid-svg-icons'

import { faUser as farUser } from '@fortawesome/free-regular-svg-icons'

library.add(
  faSearch,
  faRefresh,
  faEye,
  faEyeSlash,
  faDownload,
  faEdit,
  faTimes,
  faPlus,
  faCheck,
  faTag,
  faDollarSign,
  faUser,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faQrcode,
  faSave,
  faTrash,
  faCog,
  faInfoCircle,
  faExclamationTriangle,
  faCheckCircle,
  faTimesCircle,
  faList,
  faSignInAlt,
  faEnvelope,
  faLock,
  faKey,
  faSignOutAlt,
  faHome,
  faTachometerAlt,
  faUserCircle,
  faQuestionCircle,
  faUsers,
  faBarcode,
  faRocket,
  faBolt,
  faFolderOpen,
  faShieldHalved,
  faChartBar,
  faMobileScreenButton,
  faUserPlus,
  faBuilding,
  faWeightHanging,
  faSpinner,
  faPaperPlane,
  faArrowLeft,
  faShield,
  faTruck,
  faBox,
  faCalendar,
  faShare,
  faArrowsRotate,
  faRightToBracket,
  faRightFromBracket,
  faGaugeHigh,
  farUser
)

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('FontAwesomeIcon', FontAwesomeIcon)
})


